name: Release Plugin

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Package plugin
        id: package_plugin
        run: |
          echo ${{ steps.get_version.outputs.VERSION }} > VERSION
          zip AudioSwitcher.keypirinha-package LICENSE README.md VERSION
          cd src
          zip -r ../AudioSwitcher.keypirinha-package ./*

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: 'release-changelog-builder-config.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.8.6
        with:
          name: AudioSwitcher ${{ steps.get_version.outputs.VERSION }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'AudioSwitcher.keypirinha-package'
          artifactContentType: 'application/zip'
